import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { loadConfig } from '../config';
import { discoverFiles, filterScannedFiles, isGeneratedByContent, isGeneratedFile, walkDirectory } from '../discovery';
import { scanRepository } from '../scanner';
import { loadIgnorePatterns } from '../ignore';
import { cleanupFixture, makeFixture } from './testUtils';

let dir: string | undefined;
afterEach(() => { if (dir) cleanupFixture(dir); dir = undefined; });

describe('file discovery', () => {
    it('honors config include/exclude and gitignore/devkitignore patterns', () => {
        dir = makeFixture({
            '.devkitrc.json': JSON.stringify({ scan: { include: ['src/**'], exclude: ['src/excluded/**'] } }),
            '.gitignore': 'src/ignored.ts\n',
            '.devkitignore': 'src/private/**\n',
            'src/keep.ts': 'export const keep = 1;',
            'src/ignored.ts': 'export const ignored = 1;',
            'src/excluded/out.ts': 'export const excluded = 1;',
            'src/private/secret.ts': 'export const privateValue = 1;',
            'outside/not-included.ts': 'export const outside = 1;'
        });
        const config = loadConfig(dir);
        const result = filterScannedFiles(walkDirectory(dir), dir, config, loadIgnorePatterns(dir));
        expect(result.files.map((file) => path.relative(dir!, file).replace(/\\/g, '/'))).toEqual(['src/keep.ts']);
    });

    it('recognizes generated file content', () => {
        expect(isGeneratedByContent('// @generated\nconst x = 1;')).toBe(true);
        expect(isGeneratedByContent('const x = 1;')).toBe(false);
        expect(isGeneratedFile('src/output.ts')).toBe(false);
        expect(isGeneratedFile('src/.next/cache.js')).toBe(true);
    });
});

describe('discovery regressions (files that were silently skipped)', () => {
    it('scans source folders named build/out/vendor that are not package build output', () => {
        dir = makeFixture({
            'src/build/helper.ts': 'export const a = 1;',
            'src/commands/out/run.ts': 'export const b = 1;',
            'src/vendor/shim.ts': 'export const c = 1;',
            'dist/index.js': 'module.exports = 1;',
            'packages/web/package.json': '{"name":"web"}',
            'packages/web/build/bundle.js': 'module.exports = 1;',
            'packages/web/src/app.ts': 'export const d = 1;'
        });
        const { files } = discoverFiles(dir, loadConfig(dir));
        const relative = files.map((file) => path.relative(dir!, file).replace(/\\/g, '/')).sort();
        expect(relative).toEqual(['packages/web/src/app.ts', 'src/build/helper.ts', 'src/commands/out/run.ts', 'src/vendor/shim.ts']);
    });

    it('only treats a generated marker in the file header as generated', () => {
        const body = Array.from({ length: 40 }, (_, i) => `export const v${i} = ${i};`).join('\n');
        expect(isGeneratedByContent(`${body}\n// do not edit this list by hand\n`)).toBe(false);
        expect(isGeneratedByContent(`// Code generated by protoc. DO NOT EDIT.\n${body}`)).toBe(true);
        expect(isGeneratedByContent(`// NOTE: do not edit this list by hand\n${body}`)).toBe(false);
        expect(isGeneratedByContent(`var a=1;${'x'.repeat(8000)}`)).toBe(true);
    });

    it('keeps root-anchored .gitignore patterns anchored', () => {
        dir = makeFixture({ '.gitignore': '/lib\n', 'lib/a.ts': 'export const a = 1;', 'src/lib/b.ts': 'export const b = 1;' });
        const { files } = discoverFiles(dir, loadConfig(dir));
        expect(files.map((file) => path.relative(dir!, file).replace(/\\/g, '/'))).toEqual(['src/lib/b.ts']);
    });

    it('collects non-JS text files for the secret scan and skips lockfiles and binaries', () => {
        dir = makeFixture({
            'src/index.ts': 'export const a = 1;',
            'config/app.yaml': 'name: app',
            'package-lock.json': '{}',
            'logo.png': '\u0000PNG'
        });
        const { textFiles } = discoverFiles(dir, loadConfig(dir));
        const relative = textFiles.map((file) => path.relative(dir!, file).replace(/\\/g, '/'));
        expect(relative).toContain('config/app.yaml');
        expect(relative).not.toContain('package-lock.json');
        expect(relative).not.toContain('logo.png');
    });

    it('honors .gitignore through git, so an ignored .env is not reported as committed', () => {
        dir = makeFixture({ '.gitignore': '.env\n', '.env': 'API_TOKEN=abcdefghijklmnopqrstuvwxyz123456', 'src/index.ts': 'export const a = 1;' });
        execFileSync('git', ['init', '-q'], { cwd: dir });
        const summary = scanRepository(dir);
        expect(summary.coverage?.discoveryMethod).toBe('git');
        expect(summary.findings.some((finding) => finding.file === '.env')).toBe(false);
    });
});

describe('vendor directories stay visible', () => {
    it('does not hide a folder named vendor from analysis or the secret scan', () => {
        dir = makeFixture({
            'src/index.ts': 'export const a = 1;',
            'vendor/legacy.js': 'module.exports.legacy = 1;',
            'vendor/config.env': 'DEPLOY_TOKEN=Zk8qP2vR9xLm4Tq7Wn1Jb6Yc3Hd5Ue'
        });
        const { files, textFiles } = discoverFiles(dir, loadConfig(dir));
        const relativeFiles = files.map((file) => path.relative(dir!, file).replace(/\\/g, '/'));
        const relativeText = textFiles.map((file) => path.relative(dir!, file).replace(/\\/g, '/'));
        expect(relativeFiles).toContain('vendor/legacy.js');
        expect(relativeText).toContain('vendor/config.env');
    });
});
