/**
 * Scores the scanner against the benchmark: catch rate on the seeded repo and per-rule accuracy from
 * the seeded decoys plus the hand-labeled corpus findings.
 *
 *   npm run bench                         print the Markdown report
 *   npm run bench -- --json out.json      also write structured JSON
 *   npm run bench -- --markdown out.md    also write the Markdown report
 *   npm run bench:check                   exit 1 on a missed planted issue or a >2 point accuracy drop
 *   npm run bench -- --update-baseline    record current accuracy as the new baseline (baseline.corpus.json when corpus results exist, else baseline.json)
 *   npm run bench -- --seeded-only        ignore corpus results and labels, as CI does
 *   npm run bench -- --write-quality      write the measured accuracy into src/ruleQuality.ts (drives the default output filter)
 *   npm run bench:report                  regenerate bench/ACCURACY.md and src/ruleQuality.ts from the corpus results and labels
 */
import fs from 'node:fs';
import path from 'node:path';
import { listRules } from '../src/rules';
import { scanRepository } from '../src/scanner';
import { LABELS_DIR, readResults } from './lib/corpus';
import { SEEDED_DIR, materializeSeeded } from './lib/seeded';
import { checkGate, evaluate, formatMarkdown, readExpectations, readLabels, toBaseline, type Baseline, type BenchFinding } from './lib/scoring';

// CI has no corpus, so it gates on the seeded repo alone. With corpus results and labels present, the blended numbers are compared with their own baseline.
const SEEDED_BASELINE_PATH = path.resolve(__dirname, 'baseline.json');
const CORPUS_BASELINE_PATH = path.resolve(__dirname, 'baseline.corpus.json');
const QUALITY_PATH = path.resolve(__dirname, '..', 'src', 'ruleQuality.ts');
const QUALITY_START = '// BEGIN GENERATED RULE_ACCURACY (npm run bench -- --write-quality)';
const QUALITY_END = '// END GENERATED RULE_ACCURACY';

function option(name: string): string | undefined {
    const index = process.argv.indexOf(name);
    return index === -1 ? undefined : process.argv[index + 1];
}

function scanSeeded(): BenchFinding[] {
    const dir = materializeSeeded();
    try {
        return scanRepository(dir).findings.map(({ ruleId, severity, file, line, confidence }) => ({ ruleId, severity, file, line, confidence }));
    } finally {
        fs.rmSync(dir, { recursive: true, force: true });
    }
}

/** Wraps the report in the context a reader needs to interpret it. Generated: regenerate with `npm run bench:report`. */
function accuracyDocument(report: string, withCorpus: boolean): string {
    const corpus = (JSON.parse(fs.readFileSync(path.resolve(__dirname, 'corpus.json'), 'utf8')) as { repos: Array<{ name: string; commit: string; kind: string }> }).repos;
    return [
        '# Scanner accuracy',
        '',
        'Generated by `npm run bench:report`; do not edit by hand. See [README.md](README.md) for how the benchmark works.',
        '',
        '**Accuracy** is the share of labeled findings that were real. It is measured on the seeded repo (planted issues and clean decoys) and, when corpus results are present, on findings hand-labeled in `labels/*.jsonl` against these pinned commits:',
        '',
        ...corpus.map((repo) => `- ${repo.name} @ \`${repo.commit.slice(0, 10)}\` (${repo.kind})`),
        '',
        withCorpus
            ? 'This report includes the corpus. The corpus is scanned **without installed dependencies**, so type-based findings (TS001, ERR003) are reported at low confidence and are not labeled.'
            : 'This report is seeded-only (no corpus results were present).',
        'Labels were assigned by reading the code at each finding, with a text search for references where the claim is "nothing uses this". A finding that could not be decided was left unlabeled. A rule with fewer than 30 labels is marked "(low)": treat its percentage as an indication, not a measurement.',
        '',
        report
    ].join('\n');
}

/** Rewrites the generated RULE_ACCURACY table in src/ruleQuality.ts. Only rules with at least one scored finding are listed. */
function writeQuality(report: ReturnType<typeof evaluate>): void {
    const source = fs.readFileSync(QUALITY_PATH, 'utf8');
    const start = source.indexOf(QUALITY_START);
    const end = source.indexOf(QUALITY_END);
    if (start < 0 || end < start) throw new Error(`${QUALITY_PATH} has no generated RULE_ACCURACY block`);
    const rows = report.rules
        .filter((score) => score.accuracy !== null)
        .map((score) => `    ${score.rule}: { accuracy: ${score.accuracy}, labeled: ${score.labeled} }`);
    const block = `${QUALITY_START}\nexport const RULE_ACCURACY: Record<string, { accuracy: number; labeled: number }> = {\n${rows.join(',\n')}\n};\n`;
    fs.writeFileSync(QUALITY_PATH, source.slice(0, start) + block + source.slice(end));
}

function main(): void {
    const { expectations, lines } = readExpectations(SEEDED_DIR);
    const seededOnly = process.argv.includes('--seeded-only');
    const results = seededOnly ? {} : readResults();
    const baselinePath = Object.keys(results).length > 0 ? CORPUS_BASELINE_PATH : SEEDED_BASELINE_PATH;
    const report = evaluate({
        ruleIds: listRules().map((rule) => rule.id),
        seededFindings: scanSeeded(),
        expectations,
        markerLines: lines,
        corpusFindings: Object.fromEntries(Object.values(results).map((result) => [result.repo, result.findings])),
        labels: seededOnly ? [] : readLabels(LABELS_DIR)
    });

    const baseline: Baseline | null = fs.existsSync(baselinePath) ? (JSON.parse(fs.readFileSync(baselinePath, 'utf8')) as Baseline) : null;
    const gate = checkGate(report, baseline);
    const markdown = formatMarkdown(report, baseline);

    const jsonPath = option('--json');
    const markdownPath = option('--markdown');
    if (jsonPath) fs.writeFileSync(jsonPath, `${JSON.stringify({ report, gate }, null, 2)}\n`);
    if (markdownPath) fs.writeFileSync(markdownPath, accuracyDocument(markdown, Object.keys(results).length > 0));

    console.log(markdown);
    if (process.argv.includes('--write-quality')) {
        writeQuality(report);
        console.log(`Measured accuracy written to ${path.relative(process.cwd(), QUALITY_PATH)}`);
    }
    if (process.argv.includes('--update-baseline')) {
        fs.writeFileSync(baselinePath, `${JSON.stringify(toBaseline(report), null, 2)}\n`);
        console.log(`Baseline written to ${path.relative(process.cwd(), baselinePath)}`);
        return;
    }

    for (const warning of gate.warnings) console.warn(`warning: ${warning}`);
    if (process.argv.includes('--check')) {
        for (const failure of gate.failures) console.error(`FAIL: ${failure}`);
        if (!gate.ok) process.exitCode = 1;
        else console.log('Benchmark gate passed.');
    }
}

main();
