import type { Finding } from './types';

/** Share of a rule's findings that must be real for it to appear in the default output, in percent. */
export const TRUSTED_ACCURACY = 85;

/** Labels a rule needs before its measured accuracy can hide it: a handful of samples proves nothing. */
export const MIN_LABELS_TO_DEMOTE = 10;

/**
 * Measured accuracy per rule, from hand-labeled benchmark findings (`npm run bench`, see bench/README.md).
 * Regenerated by `npm run bench -- --write-quality`; rules that are absent have not been measured yet.
 */
export const RULE_ACCURACY: Record<string, { accuracy: number; labeled: number }> = {};

/**
 * Whether a finding is shown by default: confident (HIGH or CERTAIN) and from a rule that measured at or above
 * TRUSTED_ACCURACY. Serious security findings stay visible at MEDIUM confidence, because hiding a probable SQL
 * injection to keep the output short would make a vulnerable repository look clean. `--all` shows the rest.
 */
export function isShownByDefault(finding: Finding): boolean {
    if (finding.severity === 'INFO') return false;
    const measured = RULE_ACCURACY[finding.ruleId];
    if (measured && measured.labeled >= MIN_LABELS_TO_DEMOTE && measured.accuracy < TRUSTED_ACCURACY) return false;
    if (finding.confidence === 'CERTAIN' || finding.confidence === 'HIGH') return true;
    return finding.category === 'security' && (finding.severity === 'HIGH' || finding.severity === 'CRITICAL') && finding.confidence === 'MEDIUM';
}
